config/routes.rb
WeatherApp::Application.routes.draw do
  root to: 'static_pages#home'
  resources :forecast_areas
  devise_for :users

  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/forecast_area.rb
class ForecastArea < ActiveRecord::Base
	
	validates :zipcode, :presence => true
	validates :phone_number, :presence => true
	validates :time, :presence => true
	validates :forecast_time_zone, :presence => true
	validates :zipcode, :length => { :is => 5 }
	validates :phone_number, :length => { :is => 10}
	belongs_to :user
	# before_create :generate_and_send_verify_code

	protected

	# def generate_and_send_verify_code
	# 	self.verify_code = SecureRandom.hex(5)

 #    account_sid = 'AC1e33ca9e05cd4f86b12ffab6078464f6'
 #    auth_token = 'c451f2e1dc06ae831b8c542323099101'

 #    client = Twilio::REST::Client.new account_sid, auth_token
    
 #    client.account.sms.messages.create(
 #      :from => '+17273466568',
 #      :to => "+1#{self.phone_number}",
 #      :body => "#{self.verify_code}"
 #    )
 #  end
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :send_welcome_email

  has_one :forecast_area
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  
   def send_welcome_email
     UserMailer.welcome_email(self.email).deliver
   end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forecast_areas_controller.rb
class ForecastAreasController < ApplicationController
	before_filter :authenticate_user!
	before_filter :correct_user, :only => :destroy

	def index
		@forecast_area = current_user.forecast_area
	end

	def show
		@forecast_area = ForecastArea.find(params[:id])
	end

	def new
		@forecast_area = ForecastArea.new
	end

	def create
		@forecast_area = ForecastArea.new(params[:forecast_area])
		@forecast_area.user_id = current_user.id
		if @forecast_area.save
			flash[:success] = "New forecast area created"
			redirect_to forecast_areas_path
		else
			flash[:error] = "List creation failed"
			render 'new'
		end
	end

	def edit
		@forecast_area = ForecastArea.find(params[:id])
	end

	def update
		@forecast_area = ForecastArea.find(params[:id])
		@forecast_area.update_attributes(params[:forecast_area])
		redirect_to forecast_areas_path
	end

	def destroy
		@forecast_area.destroy
		redirect_to forecast_areas_path
	end

	private

		def correct_user
			@forecast_area = current_user.forecast_area
			redirect_to forecast_areas_path if @forecast_area.nil?
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title)
		base_title = "RainTexts"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/forecast_areas_helper.rb
module ForecastAreasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forecast_areas/_form.html.erb
<%= form_for @forecast_area do |f| %>
	<%= f.label :zipcode %>
	<%= f.text_field :zipcode %>

	<%= f.label :phone_number %>
	<%= f.phone_field :phone_number %>

	<%= f.label :time %>
	<%= f.select :time, [['6:00 AM'], ['7:00 AM'], ['8:00 AM']] %>

	<%= f.label :forecast_time_zone %>
	<%= f.select :forecast_time_zone, [['Pacific'], ['Mountain'], ['Central'], ['Eastern']] %>
<br />
<%= f.submit "Save forecast area", :class => "btn btn-primary" %>

<% end %>

app/views/forecast_areas/edit.html.erb
<h1>Update your Forecast Area</h1>
<div class="row">
  <div class="span6 offset3">
  <%= render :partial => "form", :locals => { :forecast_area => @forecast_area} %>
  </div>
</div>

app/views/forecast_areas/index.html.erb
<h2 style="margin-bottom: 10px">Your Forecast Areas</h2>
<h5 style="text-align:center; margin-bottom: 25px;">For the beta version, you are allowed to only create one forecast area</h5>

<table class="table table-bordered table-striped">
	<tr>
		<td>Zipcode</td>
		<td>Phone Number</td>
		<td>Text Time (Time Zone)</td>
		<td>Edit</td>
		<td>Delete</td>
	</tr>
<% if @forecast_area %>
	<tr>
		<td><strong><%= @forecast_area.zipcode %></strong></td>
		<td><strong><%= @forecast_area.phone_number %></strong></td>
		<td><strong><%= @forecast_area.time.to_formatted_s(:time) %><%= " (#{@forecast_area.forecast_time_zone})" %></strong> </td>
		<td><%= link_to "Edit", edit_forecast_area_path(@forecast_area), :class => "btn btn-info" %></td>
		<td><%= link_to "Delete", forecast_area_path(@forecast_area), :confirm => "Are you sure?", :method => 'delete', :class => "btn btn-danger" %></td>
	</tr>

	<% end %>
</table>
<% if @forecast_area.nil? %>
<%= link_to "Add a Forecast Area", new_forecast_area_path, :class => "btn btn-primary btn-large" %>
<% end %>

app/views/forecast_areas/new.html.erb
<h1>Create your new Forecast Area</h1>
<div class="row">
  <div class="span6 offset3">
<%= render :partial => "form", :locals => { :forecast_area => @forecast_area} %>

</div>
</div>

app/views/forecast_areas/show.html.erb
<h2>Your Forecast Areas</h2>

<table class="span6 table table-striped">
	<tr>
		<td>Zipcode</td>
		<td>Phone Number</td>
		<td>Text Time</td>
	</tr>
<@forecast_area.each do |area|
	<tr>
		<td><%= area.zipcode %></td>
		<td><%= area.phone_number %></td>
		<td><%= area.time %></td>
	</tr>

	<% end %>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
  <small>
    <%= link_to "RainyText", root_path %> by Shail Patel
  </small>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "RainyText", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to current_user.email, forecast_areas_path %></li>
          <% end %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if current_user %>
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_ie.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/ie' %>
  </head>
  <body>
    <div class="container">
        <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="hero-unit">
<h1 class="help">About RainyText</h1>
<p>
	Have you ever been in a rush and not had time to check the weather? Find yourself walking out the door into a downpour without an umbrella? Well, no more! RainyText will send you a morning text to remind you to grab an umbrella if it's going to rain!
</p> 
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="hero-unit">
<h1 class="help">Contact RainyText</h1>
<p>Email: nomorerain@rainytext.com </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="hero-unit">
	<h1 class="help">RainyText Help</h1>
	<h2 class="helph2">How does this work?</h2>
	<ol style="margin-left:40px">
		<li>Sign up for an account with your e-mail and password.</li>
		<li>Click the "Your Forecast Areas" button.</li>
		<li>Click the "Add a Forecast Area" button.</li>
		<li>Enter the appropriate information, click "Submit", and you'll never get drenched in the rain again!</li>
	</ol>

	<h2 class="helph2">More Questions? Suggestions?</h2>
	<text class="helptext">Direct them to <strong>rainytexthelp@rainytext.com</strong>!</text>
	<br />
	<br />
	<text class="helptext">
	We'll get back to you as soon as possible!</text>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to RainyText</h1>
	<h2>
		Getting soaked in the rain?
 		We solve all your problems by reminding you to grab your umbrella before it starts raining!
 	</h2>
 	<% if current_user %>
 	<%= link_to "Your Forecast Areas", forecast_areas_path , class: "btn btn-large btn-primary" %>
 	<% else %>

 	<div class="row homepagetable">
 	<div class="span3 homerows">
 		<h3>Already a member?</h3>
 		<%= link_to "Sign in now!", new_user_session_path , class: "btn btn-large btn-success homesign" %>
 	</div>

 	<div class="span3" style="margin-right:-10px;">
 		<h3>First time at RainyText?</h3>
 		<%= link_to "Sign up now!", new_user_registration_path , class: "btn btn-large btn-primary homesign" %>
 	</div>
 	</div>
 	<% end %>
</div>

 
 